# Generated by Django 3.1.4 on 2020-12-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcupacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoocupacao_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoocupacao_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Ocupação',
                'db_table': 'tipo_ocupacao',
            },
        ),
        migrations.CreateModel(
            name='OcupacaoLeitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocupacaoleitos_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocupacaoleitos_modified', to=settings.AUTH_USER_MODEL)),
                ('tipo_ocupacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disc.tipoocupacao')),
            ],
            options={
                'verbose_name_plural': 'Quantidade de Ocupações',
                'db_table': 'ocupacao_leito',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('data_ocupacao', models.DateField()),
                ('leito_ocupado', models.IntegerField(blank=True, null=True)),
                ('leito_disponivel', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocupacao_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocupacao_modified', to=settings.AUTH_USER_MODEL)),
                ('tipo_ocupacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disc.tipoocupacao')),
            ],
            options={
                'verbose_name_plural': 'Ocupação',
                'db_table': 'ocupacao',
            },
        ),
    ]
