# Generated by Django 3.1.4 on 2020-12-14 07:49

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(blank=True, default=0, verbose_name='Número (Ordem)')),
                ('data_liberacao', models.DateField(blank=True, null=True, verbose_name='Data de Liberação')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aula_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aulas',
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Curso')),
                ('description', models.TextField(blank=True, verbose_name='Descrição Simples')),
                ('about', models.TextField(blank=True, verbose_name='Sobre o Curso')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='Imagem do Curso')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso_modified', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('secretaria', models.CharField(max_length=255, verbose_name='Secretaria')),
                ('diretoria', models.CharField(max_length=255, verbose_name='Diretoria')),
                ('divisao', models.CharField(max_length=255, verbose_name='Divisão')),
                ('setor', models.CharField(max_length=255, verbose_name='Setor')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Setores',
                'db_table': 'setor',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('acesso', models.IntegerField(blank=True, choices=[(1, 'Professor'), (0, 'Aluno')], null=True, verbose_name='Tipo de Acesso')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whats', models.CharField(max_length=15, verbose_name='WhatsApp')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_modified', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ead.setor', verbose_name='Setor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('embedded', models.TextField(blank=True, verbose_name='Vídeo embedded')),
                ('file', models.FileField(blank=True, null=True, upload_to='aulas/materiais')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='ead.aula', verbose_name='Aula')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Materiais',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=1)),
                ('situacao', models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=1, verbose_name='Situação')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='ead.curso', verbose_name='Curso')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricao',
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='ead.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aula_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
