# Generated by Django 3.1.4 on 2020-12-14 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.IntegerField()),
                ('start', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
