# Generated by Django 3.1.4 on 2020-12-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0002_auto_20201214_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'verbose_name_plural': 'Movimentos'},
        ),
        migrations.RenameField(
            model_name='movimento',
            old_name='objeto',
            new_name='objeto_id',
        ),
        migrations.AddField(
            model_name='movimento',
            name='objeto_nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimento',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='movimento',
            table='movimento',
        ),
    ]
